import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

const editions = [
  {
    year: 2026, month: 3, title: "March 2026", slug: "2026-03", published: true,
    winners: [
      { filmTitle: "Assembled Worlds", recipient: "Kaja Vidič", category: "BEST DANCE FILM, SHORT" },
      { filmTitle: "Dancing Streets - On the Road in Nepal / Tanzende Strassen - Unterwegs in Nepal", recipient: "Martin Kemeter", category: "BEST DOCUMENTARY" },
      { filmTitle: "Forced Renewables", recipient: "Francisco Javier Fernández Bordonada", category: "BEST ENVIRONMENT AND CLIMATE, FEATURE" },
      { filmTitle: "Grandpa's Tales", recipient: "Tim Klein", category: "BEST HISTORY FILM" },
      { filmTitle: "Kral Günlükleri ve Urartian Çivi Norması", recipient: "A.Kadir Özdemir", category: "BEST SHORT DOCUMENTARY" },
      { filmTitle: "MANIFESTO", recipient: "Sergio Nolasco", category: "BEST COMMERCIAL & ADVERTISING" },
      { filmTitle: "Mental", recipient: "Laura Gross", category: "BEST COMEDY, FEATURE" },
      { filmTitle: "Oceans Of Hope", recipient: "El Rhodes", category: "BEST HEALTH AND MEDICINE SHORT FILM" },
      { filmTitle: "Pangalactic Theatre presents Once upon a time in a cave", recipient: "Patrick Praschma", category: "BEST ARTIST FEATURE FILM" },
      { filmTitle: "Salamo", recipient: "Randi Becker", category: "BEST ARTIST SHORT FILM" },
      { filmTitle: "Shimmer", recipient: "Try Us Film", category: "BEST SHORT FILM" },
      { filmTitle: "TORN", recipient: "Gonca de Haas", category: "BEST ACTRESS - SHORT FILM" },
      { filmTitle: "The Fabric Of Spaces", recipient: "Brenda Jean Yong", category: "BEST FASHION FILM" },
      { filmTitle: "Themis is Tired", recipient: "Ilya Demutsky", category: "BEST DIRECTOR - SHORT FILM" },
      { filmTitle: "Themis is Tired", recipient: "Boris Chistyakov", category: "BEST ACTOR - SHORT FILM" },
      { filmTitle: "VIEW", recipient: "Ina Gagola", category: "BEST EXPERIMENTAL FILM" },
      { filmTitle: "Yokaitopia", recipient: "Glenna Burmer", category: "BEST ANIMATION" },
      { filmTitle: "And the storm dreamed of horses", recipient: "Coralie Hina Gourdon", category: "HONORABLE MENTION" },
      { filmTitle: "Ein Deutscher Film", recipient: "Jannis Welters", category: "HONORABLE MENTION" },
      { filmTitle: "Enemy Heroes", recipient: "Mark Diamond", category: "HONORABLE MENTION" },
      { filmTitle: "LEMON", recipient: "Ami Sakurai", category: "HONORABLE MENTION" },
      { filmTitle: "La Rose Blanche", recipient: "Bogdan Tolj", category: "HONORABLE MENTION" },
      { filmTitle: "Portrait of Traces", recipient: "Hecabe SE Company", category: "HONORABLE MENTION" },
      { filmTitle: "Running errands", recipient: "Max Koller", category: "HONORABLE MENTION" },
      { filmTitle: "The Treasure of the One-Armed Bandit", recipient: "Tim Osterloh", category: "HONORABLE MENTION" },
      { filmTitle: "VEKK", recipient: "Thea Bay", category: "HONORABLE MENTION" },
      { filmTitle: "Vanitas", recipient: "Marcie Begleiter", category: "HONORABLE MENTION" },
      { filmTitle: "fluid", recipient: "Ingrid Gans", category: "HONORABLE MENTION" },
      { filmTitle: "last week", recipient: "Stephan Lichtensteiger", category: "HONORABLE MENTION" },
    ],
  },
  {
    year: 2026, month: 2, title: "February 2026", slug: "2026-02", published: true,
    winners: [
      { filmTitle: "A song to Louise", recipient: "Romain Veil", category: "BEST SHORT FILM" },
      { filmTitle: "Bagatelle II: La Murisserie", recipient: "Ashley Defoe", category: "BEST DANCE FILM" },
      { filmTitle: "C I R C L E / S", recipient: "Reece Ewing", category: "BEST MUSIC SCORE SHORT FILM" },
      { filmTitle: "C I R C L E / S", recipient: "Reece Ewing", category: "BEST MUSIC VIDEO" },
      { filmTitle: "Cicada", recipient: "Julia Wilkins", category: "BEST EXPERIMENTAL FILM" },
      { filmTitle: "Enemy Heroes", recipient: "Mark Diamond", category: "BEST HISTORY FILM" },
      { filmTitle: "Foot in the door", recipient: "Dimitri Limpert", category: "BEST COMEDY SHORT FILM" },
      { filmTitle: "Fresh Powder", recipient: "Katrin Katz Köbbert", category: "BEST ACTRESS – SHORT FILM" },
      { filmTitle: "Model Professor", recipient: "Peter Brinson", category: "BEST SCIENCE FICTION FILM" },
      { filmTitle: "Obstinate Seasons", recipient: "Gail Malbete", category: "BEST ENVIRONMENT AND CLIMATE" },
      { filmTitle: "Overlooked", recipient: "Luca Müller", category: "BEST ACTOR – SHORT FILM" },
      { filmTitle: "Perfume Advertising – Sudden Banality", recipient: "Savio Liborio Ciufo", category: "BEST COMMERCIAL & ADVERTISING" },
      { filmTitle: "The Quest For The Golden Dragon", recipient: "Tom Whiteley", category: "BEST MUSIC SCORE SHORT FILM" },
      { filmTitle: "The Silent Retreat", recipient: "Mason Mirabile", category: "BEST STUDENT FILM" },
      { filmTitle: "The Werewolf in the Waves", recipient: "Soleil Moon Frye", category: "BEST DOCUMENTARY" },
      { filmTitle: "Vincente", recipient: "Vanessa Riecke", category: "BEST ANIMATION" },
      { filmTitle: "War of the Weisses", recipient: "Vickie Tanner", category: "BEST DIRECTOR – SHORT FILM" },
      { filmTitle: "Where Is Your Home, Winston?", recipient: "KIEKU Production", category: "BEST FAMILY AND CHILDREN FRIENDLY FILM" },
      { filmTitle: "HOMELESSNESS IN AMERICA", recipient: "Asad Sheikh", category: "HONORABLE MENTION" },
      { filmTitle: "My name is Ausländer", recipient: "Giovanna Wolney", category: "HONORABLE MENTION" },
      { filmTitle: "MÀQUINA", recipient: "Joaquim Pujol", category: "HONORABLE MENTION" },
      { filmTitle: "The Humanity!", recipient: "David Morley", category: "HONORABLE MENTION" },
      { filmTitle: "Trace", recipient: "Michele Evouna", category: "HONORABLE MENTION" },
      { filmTitle: "remember when I told you everything", recipient: "Paula Rae Gibson", category: "HONORABLE MENTION" },
    ],
  },
  {
    year: 2026, month: 1, title: "January 2026", slug: "2026-01", published: true,
    winners: [
      { filmTitle: "The Breath of Nyungwe", recipient: "Edward Lee", category: "BEST TRAVEL FILM" },
      { filmTitle: "Gardens of Fez", recipient: "Heidi Vogels", category: "BEST ENVIRONMENT AND CLIMATE" },
      { filmTitle: "Korakuen", recipient: "Mia Ando", category: "BEST DIRECTOR – SHORT FILM" },
      { filmTitle: "A day in April", recipient: "Frank Ernst Lesting", category: "BEST FEATURE FILM" },
      { filmTitle: "No MiLk TOdaY – HerMan's Hermits", recipient: "Alakfilms", category: "BEST EXPERIMENTAL FILM" },
      { filmTitle: "Going Crazy by Orange Soda", recipient: "Milena Kaltenbach", category: "BEST MUSIC VIDEO" },
      { filmTitle: "Who Broke The Vase?", recipient: "David Aledo Yanguas", category: "BEST STUDENT FILM" },
      { filmTitle: "No Mercy", recipient: "Sophiane Afroun", category: "BEST HUMAN RIGHTS FILM" },
      { filmTitle: "El día que me quieras", recipient: "Matias Mera", category: "BEST SHORT FILM" },
      { filmTitle: "Threatening letter on hold", recipient: "Thomas Schuster", category: "BEST SHORT FILM" },
      { filmTitle: "COMPETITION OF A LIFETIME", recipient: "Antonio La Regina", category: "BEST DOCUMENTARY" },
      { filmTitle: "Dignified", recipient: "Elke Frey", category: "BEST DOCUMENTARY" },
      { filmTitle: "Nothing to See Here: Watts", recipient: "Michael Soenen", category: "BEST FIRST TIME DIRECTOR" },
      { filmTitle: "Nothing to See Here: Watts", recipient: "Michael Soenen", category: "BEST CINEMATOGRAPHY" },
      { filmTitle: "Nothing to See Here: Watts", recipient: "Michael Soenen", category: "BEST MUSIC SCORE FEATURE FILM" },
      { filmTitle: "Nothing to See Here: Watts", recipient: "Michael Soenen", category: "BEST GENDER EQUALITY" },
      { filmTitle: "8 seconds", recipient: "Jean-Marie Vinclair", category: "BEST DOCUMENTARY" },
      { filmTitle: "Atlantic Shadows", recipient: "Kostiantyn Mishchenko, Valeri Zayets", category: "BEST SHORT DOCUMENTARY" },
      { filmTitle: "WOMB SPACE", recipient: "Marisa Papen, Michael Chichi", category: "BEST MUSIC SCORE SHORT FILM" },
      { filmTitle: "The hand of god", recipient: "Jong In Shin, Sung In Shin", category: "BEST COMEDY SHORT FILM" },
      { filmTitle: "People Can Change", recipient: "Allen Brooks", category: "HONORABLE MENTION" },
      { filmTitle: "LAYLA", recipient: "Sondos Yasser", category: "HONORABLE MENTION" },
      { filmTitle: "Under tears of wine", recipient: "Joy Davillé", category: "HONORABLE MENTION" },
      { filmTitle: "darlings of fortune", recipient: "Melike Yağız-Baxant", category: "HONORABLE MENTION" },
      { filmTitle: "pre•de•ter•mined brea•king point", recipient: "Paula Leitenberger", category: "HONORABLE MENTION" },
      { filmTitle: "What Comes Before the Fall?", recipient: "Jonathan Anand Victor", category: "HONORABLE MENTION" },
      { filmTitle: "Rooted", recipient: "Sailesh Rajan Israni", category: "HONORABLE MENTION" },
    ],
  },
  {
    year: 2025, month: 12, title: "December 2025", slug: "2025-12", published: true,
    winners: [
      { filmTitle: "60 Pounds of Home", recipient: "Michael Eibl", category: "BEST HISTORY FILM" },
      { filmTitle: "60 Pounds of Home", recipient: "Michael Eibl", category: "BEST FIRST TIME DIRECTOR" },
      { filmTitle: "Rice & Sugar", recipient: "Phillip O'Leary", category: "BEST CINEMATOGRAPHY" },
      { filmTitle: "Taming the Fish", recipient: "Jiancheng Ding", category: "BEST DOCUMENTARY" },
      { filmTitle: "The Automotive Human", recipient: "Reinhard Seiss", category: "BEST ENVIRONMENT AND CLIMATE" },
      { filmTitle: "Most Longest Day", recipient: "Vis Vitalis", category: "BEST FEATURE FILM" },
      { filmTitle: "Snow Over Kigali", recipient: "Kerim Esen", category: "BEST FAMILY AND CHILDREN FRIENDLY FILM" },
      { filmTitle: "Waltz of the Free World", recipient: "Amir Ghandi", category: "BEST MUSIC VIDEO" },
      { filmTitle: "Texas Strange", recipient: "Justin Eugene Evans", category: "BEST SCIENCE FICTION" },
      { filmTitle: "Other I", recipient: "Alina Popescu", category: "BEST ANIMATION" },
      { filmTitle: "Elemental Feelings", recipient: "Charlie Tweed", category: "BEST EXPERIMENTAL FILM" },
      { filmTitle: "ANTIOCH – On the trails of history", recipient: "Lucas Yalaza", category: "BEST STUDENT FILM" },
      { filmTitle: "The Liars of Black Mountain Road", recipient: "Parker Croft", category: "BEST SHORT FILM" },
      { filmTitle: "FEIBO AMIDST FLOWERS", recipient: "斌 李", category: "BEST SHORT DOCUMENTARY" },
      { filmTitle: "PUNKIE", recipient: "Audrey Olsen", category: "HONORABLE MENTION" },
    ],
  },
  {
    year: 2025, month: 11, title: "November 2025", slug: "2025-11", published: true,
    winners: [
      { filmTitle: "Meridian Transmissions", recipient: "Eric Patrick", category: "BEST VR AND 360 FILM" },
      { filmTitle: "KILLER THREADS", recipient: "Miranda Del Carmen Garza, Yumi Yuzuriha", category: "BEST STUDENT FILM" },
      { filmTitle: "KILLER THREADS", recipient: "Will Nunziata", category: "BEST ACTOR – SHORT FILM" },
      { filmTitle: "I Was Still Here.", recipient: "Dennis Büschemann", category: "BEST ANIMATION" },
      { filmTitle: "Wake Up, Dolores!", recipient: "Dan James Rathke", category: "BEST SCIENCE FICTION FILM" },
      { filmTitle: "Assessment", recipient: "Waldemar Schleicher", category: "BEST COMEDY SHORT FILM" },
      { filmTitle: "BRAINBUGS", recipient: "Jon Westling", category: "BEST FEATURE FILM" },
      { filmTitle: "The Space Between", recipient: "Linda Tümmler", category: "BEST CINEMATOGRAPHY" },
      { filmTitle: "Baccanti", recipient: "Emma Scarafiotti", category: "BEST EXPERIMENTAL FILM" },
      { filmTitle: "Access All Areas — The Tower", recipient: "Mireille Solomon", category: "BEST DANCE FILM" },
      { filmTitle: "Between the sky and the yurt", recipient: "Mona Mongoljin Schmauß", category: "BEST TRAVEL FILM" },
      { filmTitle: "The Uniform", recipient: "Dylan Gary", category: "BEST DIRECTOR – SHORT FILM" },
      { filmTitle: "The Quiet Diplomat", recipient: "Charles Lyons", category: "BEST DOCUMENTARY" },
      { filmTitle: "Chingona", recipient: "Rupert Höller, Harlock Chavez", category: "BEST MUSIC VIDEO" },
      { filmTitle: "See You, Palestine", recipient: "Jürgen Baums", category: "BEST SHORT DOCUMENTARY" },
      { filmTitle: "Red plague", recipient: "Aleksandra Fudala", category: "BEST SHORT FILM" },
      { filmTitle: "The Uniform", recipient: "Dylan Gary", category: "BEST SHORT FILM" },
    ],
  },
  {
    year: 2025, month: 10, title: "October 2025", slug: "2025-10", published: true,
    winners: [
      { filmTitle: "Disorder", recipient: "Joshua Meszaros", category: "BEST FIRST TIME DIRECTOR" },
      { filmTitle: "His Theater", recipient: "Anastasiia Kukharieva", category: "BEST STUDENT FILM" },
      { filmTitle: "Leonard Cohen in the Eating Disorder Ward", recipient: "Lucas Crawford", category: "BEST HEALTH AND MEDICINE FILM" },
      { filmTitle: "Generated by RR5485", recipient: "Oscar Ballyvolane", category: "BEST SCIENCE FICTION FILM" },
      { filmTitle: "A Film by Roland Wehap", recipient: "Roland Wehap", category: "BEST COMEDY SHORT FILM" },
      { filmTitle: "No Vacancy", recipient: "Carolyn Gair", category: "BEST ANIMATION" },
      { filmTitle: "The Ineffable Fixing of the Volatile", recipient: "Arepo", category: "BEST EXPERIMENTAL FILM" },
      { filmTitle: "Zesi", recipient: "Panagiotis Papafragkos", category: "BEST DANCE FILM" },
      { filmTitle: "San Esteban: Freedom, Mysticism and Nopales", recipient: "Francisco Herrera", category: "BEST SHORT DOCUMENTARY" },
      { filmTitle: "Where to Escape?", recipient: "Ömür Akif Dinç, İsmail Berk Karakaya", category: "BEST SHORT FILM" },
      { filmTitle: "I'm Leaving and I'm Becoming Pope", recipient: "Antonello Carbone", category: "BEST DOCUMENTARY" },
      { filmTitle: "The Influencers and the Baba Jaga of Gentrification", recipient: "Irene Ros", category: "BEST MUSIC VIDEO" },
    ],
  },
  {
    year: 2025, month: 9, title: "September 2025", slug: "2025-09", published: true,
    winners: [
      { filmTitle: "Toward Entropy 360", recipient: "Jaewook Lee", category: "BEST VR AND 360 FILM" },
      { filmTitle: "Quit Laughing God, This is Serious!", recipient: "Michael Weissman", category: "BEST FAMILY AND CHILDREN FRIENDLY FILM" },
      { filmTitle: "Many Die Too Late", recipient: "Julian Bonnin", category: "BEST EXPERIMENTAL FILM" },
      { filmTitle: "CARNE: The Unsustainable Footprint", recipient: "Hugo de Almeida", category: "BEST ENVIRONMENT AND CLIMATE" },
      { filmTitle: "In The Middle", recipient: "Saba Khatami", category: "BEST DANCE FILM" },
      { filmTitle: "RAKUGO KARMA", recipient: "Kyosuke Enokizono", category: "BEST COMEDY FEATURE FILM" },
      { filmTitle: "THE TENDER ONES WILL TRIUMPH", recipient: "Keira Lintu", category: "BEST ACTRESS – SHORT FILM" },
      { filmTitle: "FREESTYLE – On top of the nail", recipient: "Alexej Getmann, Jan Odenthal", category: "BEST DOCUMENTARY" },
      { filmTitle: "Dabbawala Berlin: Bicycle Stories", recipient: "Robin Csodó, Pavel Pantin", category: "BEST SHORT DOCUMENTARY" },
      { filmTitle: "\"THE RECIPE TO SAVE HUMANITY\"", recipient: "Yosef Tager", category: "BEST FEATURE FILM" },
      { filmTitle: "Romancing Sydney", recipient: "Anmol Mishra", category: "BEST FIRST TIME DIRECTOR" },
      { filmTitle: "Gyre", recipient: "Michael Dawidowicz", category: "BEST STUDENT FILM" },
      { filmTitle: "Wukong Couriers", recipient: "Peter Gabriel Gagnon", category: "BEST SHORT FILM – EX AEQUO" },
      { filmTitle: "Selfie, Please", recipient: "Anu Singh Choudhary", category: "BEST SHORT FILM – EX AEQUO" },
    ],
  },
  {
    year: 2025, month: 8, title: "August 2025", slug: "2025-08", published: true,
    winners: [
      { filmTitle: "What We Carried", recipient: "Carolina Pereira", category: "BEST FIRST TIME DIRECTOR" },
      { filmTitle: "What We Carried", recipient: "Carolina Pereira", category: "BEST GENDER EQUALITY" },
      { filmTitle: "everything i wanted to tell you", recipient: "Jessie Garon, Slone McGowan", category: "BEST DANCE FILM" },
      { filmTitle: "Wind Beyond", recipient: "Seo Young Hong", category: "BEST STUDENT FILM" },
      { filmTitle: "Ball Lightning", recipient: "Catriona Trina Baker", category: "BEST ANIMATION" },
      { filmTitle: "This Calm Can Turn into a Storm", recipient: "Antonia Colodro", category: "BEST SHORT DOCUMENTARY" },
      { filmTitle: "DELULU", recipient: "Athan Tom Sklavos", category: "BEST SHORT FILM" },
      { filmTitle: "Fist Bump", recipient: "Madeleine Farley", category: "BEST DOCUMENTARY" },
      { filmTitle: "Hello boss, I'm menstruating", recipient: "Hello boss, I'm menstruating", category: "BEST COMEDY SHORT FILM" },
      { filmTitle: "Ritu Kamini (The Earth)", recipient: "Zahid Hossain", category: "BEST ENVIRONMENT AND CLIMATE" },
      { filmTitle: "Agnosia", recipient: "James Autery", category: "BEST HEALTH AND MEDICINE FILM" },
      { filmTitle: "My Car is Filled with Moisture", recipient: "Danny Helme", category: "BEST EXPERIMENTAL FILM" },
      { filmTitle: "Ukraine, Ukraine", recipient: "Ukraine, Ukraine", category: "BEST MUSIC VIDEO" },
    ],
  },
  {
    year: 2025, month: 7, title: "July 2025", slug: "2025-07", published: true,
    winners: [
      { filmTitle: "Goodbye To God", recipient: "George Jonathan Jenkins", category: "BEST ANIMATION" },
      { filmTitle: "Kielo", recipient: "Sinem Kayacan, Janina Rajakangas", category: "BEST FAMILY AND CHILDREN FRIENDLY FILM" },
      { filmTitle: "Ida Rolf – Mother of Fascia", recipient: "Aleš Urbanczik", category: "BEST HISTORY FILM" },
      { filmTitle: "Uprising of Youth", recipient: "Simon Marian Hoffmann", category: "BEST ENVIRONMENT AND CLIMATE" },
      { filmTitle: "TRASHZILLA", recipient: "Shana Nielsen, Andie Neumann", category: "BEST ENVIRONMENT AND CLIMATE, SHORT" },
      { filmTitle: "A Dinner to Remember", recipient: "Leonardo Re", category: "BEST COMEDY FEATURE FILM" },
      { filmTitle: "Ten things to talk about with your crush", recipient: "Vico Herurbi", category: "BEST COMEDY SHORT FILM" },
      { filmTitle: "Complete sense of freedom", recipient: "Karlo Mitok", category: "BEST TRAVEL FILM" },
      { filmTitle: "The corner.701", recipient: "Stella Degli-Kassis", category: "BEST FEATURE FILM" },
      { filmTitle: "Bittersweet Çay", recipient: "Demet Şener", category: "BEST FIRST TIME DIRECTOR" },
      { filmTitle: "THE PROJECT", recipient: "Margaux Chouraqui", category: "BEST DOCUMENTARY" },
      { filmTitle: "Nebbia", recipient: "Lisa Rovo", category: "BEST SHORT FILM" },
      { filmTitle: "Exist", recipient: "Viktor Telegin, Markus Bengtsson", category: "BEST SHORT DOCUMENTARY" },
      { filmTitle: "Rat Race – 24/7 DIva Heaven", recipient: "Stefanie Schmid Rincon", category: "BEST MUSIC VIDEO" },
    ],
  },
  {
    year: 2025, month: 6, title: "June 2025", slug: "2025-06", published: true,
    winners: [
      { filmTitle: "Mutation", recipient: "Carlo Ayhllón", category: "BEST MUSIC SCORE FEATURE FILM" },
      { filmTitle: "The Silence within (Lautlos)", recipient: "Christian Peschken", category: "BEST HEALTH AND MEDICINE FILM" },
      { filmTitle: "Les filles et les garçons de mon âge", recipient: "Giovanni Princigalli", category: "BEST FAMILY AND CHILDREN FRIENDLY FILM" },
      { filmTitle: "Europe's lithium paradox", recipient: "Stijn van Baarle", category: "BEST ENVIRONMENT AND CLIMATE" },
      { filmTitle: "Tricorder.Zero™ Online Ad", recipient: "Marcus C.B. Soori", category: "BEST COMMERCIAL & ADVERTISING" },
      { filmTitle: "American Comedy", recipient: "Linda S. Wong", category: "BEST ACTRESS – FEATURE FILM" },
      { filmTitle: "TPW 7", recipient: "Michael Laux", category: "BEST ACTOR – SHORT FILM" },
      { filmTitle: "Take it Back", recipient: "Laure Sullivan", category: "BEST MUSIC VIDEO" },
      { filmTitle: "Hofedl 18", recipient: "Carina Spreitzer", category: "BEST SHORT DOCUMENTARY" },
      { filmTitle: "Knot", recipient: "Lucas Mendes de Oliveira", category: "BEST FEATURE FILM" },
      { filmTitle: "THE RECLUSE DONGPO", recipient: "Zhong Tie, Ye Bian", category: "BEST VR AND 360" },
      { filmTitle: "Keyo? (Why?)", recipient: "Aparup Agarwala", category: "BEST FIRST TIME DIRECTOR" },
      { filmTitle: "Not a Rookie Sandpipper", recipient: "Jens Møller, Lei Zhang", category: "BEST ANIMATION" },
      { filmTitle: "Wandering", recipient: "Nuoya Ge", category: "BEST STUDENT FILM" },
      { filmTitle: "Toil and Spin", recipient: "Maureen Zent", category: "BEST EXPERIMENTAL FILM" },
      { filmTitle: "NANI", recipient: "Mainak Dhar", category: "BEST SHORT FILM" },
      { filmTitle: "Keep Quiet and Forgive", recipient: "Sarah McClure", category: "BEST DOCUMENTARY" },
    ],
  },
  {
    year: 2025, month: 5, title: "May 2025", slug: "2025-05", published: true,
    winners: [
      { filmTitle: "Gihan", recipient: "Hadeer Omar", category: "BEST VR AND 360 FILM" },
      { filmTitle: "Loving Lovis", recipient: "Wei Tan", category: "BEST DIRECTOR – FEATURE FILM" },
      { filmTitle: "The Black Rock", recipient: "Andrew Games", category: "BEST HISTORY FILM" },
      { filmTitle: "DYNAMICS", recipient: "Teo Baehler", category: "BEST EXPERIMENTAL FILM" },
      { filmTitle: "Sexy Time Soup", recipient: "Gabrielle Pfeiffer", category: "BEST COMEDY SHORT FILM" },
      { filmTitle: "BREAK THE SILENCE", recipient: "Dax Phelan", category: "BEST COMMERCIAL & ADVERTISING" },
      { filmTitle: "Loving Lovis", recipient: "Wiktoria Bergiel", category: "BEST ACTRESS – FEATURE FILM" },
      { filmTitle: "Loving Lovis", recipient: "Dawid Tysowski", category: "BEST ACTOR – FEATURE FILM" },
      { filmTitle: "Reminiscence", recipient: "Alexey Kolbekhin", category: "BEST FIRST TIME DIRECTOR" },
      { filmTitle: "Papa", recipient: "Margarita Grillis", category: "BEST ACTRESS – SHORT FILM" },
      { filmTitle: "Papa", recipient: "Gregory Cox", category: "BEST ACTOR – SHORT FILM" },
      { filmTitle: "The Taste of Greed", recipient: "Senthooran Ramanathan", category: "BEST DIRECTOR – SHORT FILM" },
      { filmTitle: "Chaton – From the Future", recipient: "Marcus CB Soori", category: "BEST ANIMATION" },
      { filmTitle: "喜辰晨 Voision Xi – Kagi 鍵", recipient: "Li Pan, Luozhonghan", category: "BEST MUSIC VIDEO" },
      { filmTitle: "Land of the Mustaches", recipient: "Leon Joosen", category: "BEST FEATURE FILM" },
      { filmTitle: "NADO", recipient: "Daniele Farina", category: "BEST DOCUMENTARY" },
      { filmTitle: "GIFT", recipient: "Lenka Zhang", category: "BEST STUDENT FILM" },
      { filmTitle: "Tokyo Tea Tango", recipient: "Robert Chmielewski", category: "BEST SHORT FILM" },
    ],
  },
  {
    year: 2025, month: 4, title: "April 2025", slug: "2025-04", published: true,
    winners: [
      { filmTitle: "By the Shore", recipient: "Rojin Aslan Vesek", category: "BEST ENVIRONMENT AND CLIMATE" },
      { filmTitle: "To The End", recipient: "Ruiying Sun", category: "BEST SCIENCE FICTION FILM" },
      { filmTitle: "What do you believe in? (Matosinhos)", recipient: "Nelson Carvalheiro", category: "BEST TRAVEL SHORT FILM" },
      { filmTitle: "GODMODE_ Digital murder", recipient: "Emil H Jonsvik", category: "BEST FEATURE FILM" },
      { filmTitle: "LAMIA – Cobra", recipient: "Ronen Eldar", category: "BEST MUSIC VIDEO" },
      { filmTitle: "amniotic artheraπ", recipient: "Konrad Mihat", category: "BEST VR AND 360 FILM" },
      { filmTitle: "DEADBEAT", recipient: "Louis Holmes", category: "BEST FIRST TIME DIRECTOR" },
      { filmTitle: "Fufu in Paradise", recipient: "Vijchika Udomsrianan", category: "BEST EXPERIMENTAL FILM" },
      { filmTitle: "SOMNAMBUL", recipient: "Benno Blome", category: "BEST GENDER EQUALITY" },
      { filmTitle: "SOCRATES", recipient: "Ken Sagoes", category: "BEST SHORT FILM" },
      { filmTitle: "KINDness", recipient: "Max Fritzsching", category: "BEST ACTOR – SHORT FILM" },
      { filmTitle: "Leave behind", recipient: "Isabel Bernal", category: "BEST ACTRESS – SHORT FILM" },
      { filmTitle: "Changes in Light", recipient: "Anna Macdonald", category: "BEST SHORT DOCUMENTARY" },
      { filmTitle: "BE", recipient: "Chonger Wu", category: "BEST ANIMATION" },
      { filmTitle: "Gars am Inn, 10 Postcards", recipient: "Matija Lujic", category: "BEST STUDENT FILM" },
      { filmTitle: "CATCH THE WIND ST IVES IN THE 60S", recipient: "Diana Taylor", category: "BEST DOCUMENTARY" },
      { filmTitle: "Last Man Bluffing", recipient: "Simeon Schmidt", category: "BEST SHORT FILM" },
    ],
  },
  {
    year: 2025, month: 3, title: "March 2025", slug: "2025-03", published: true,
    winners: [
      { filmTitle: "Sofia Portanet – Lust feat. Tobias Bamborschke", recipient: "Béla Baptiste", category: "BEST EXPERIMENTAL FILM – MUSIC" },
      { filmTitle: "Matilda and the Brave Escape", recipient: "Surge Activism", category: "BEST ANIMATION" },
      { filmTitle: "Fata Morgana", recipient: "Mehrdad Bahrain", category: "BEST STUDENT FILM" },
      { filmTitle: "Directions To The Other Side Of The World", recipient: "Derrick Belcham", category: "BEST DANCE FILM" },
      { filmTitle: "The Sea", recipient: "Douglas Rosenberg", category: "BEST FEATURE FILM" },
      { filmTitle: "THE FAREWELL", recipient: "Hüseyin Gürses", category: "BEST FIRST TIME DIRECTOR" },
      { filmTitle: "LA LIXEIRA – the invisibles' dignity", recipient: "Guido Galante", category: "BEST SHORT DOCUMENTARY" },
      { filmTitle: "Tangle", recipient: "Carla Hoogewijs and Frank Stevens", category: "BEST EXPERIMENTAL FILM" },
      { filmTitle: "Junction", recipient: "Luciana Salinas, Trina Mulligan, Caitlyn Spiritus", category: "BEST CINEMATOGRAPHY" },
      { filmTitle: "Unerreichbar nah", recipient: "Katja Müller", category: "BEST HEALTH AND MEDICINE FILM" },
      { filmTitle: "The Flower Seller", recipient: "Bertrand Alfonso", category: "BEST COMMERCIAL AND ADVERTISING" },
      { filmTitle: "Bear Medicine Society", recipient: "Jodi Rave Spotted Bear", category: "BEST HISTORY FILM" },
      { filmTitle: "METEORA", recipient: "Pathos Distribution", category: "BEST FAMILY AND CHILDREN FRIENDLY FILM" },
      { filmTitle: "IN HER SKIN", recipient: "Kazım", category: "BEST SCIENCE FICTION FILM" },
      { filmTitle: "Sofia Portanet – Entre Nos Lèvres", recipient: "Béla Baptiste", category: "BEST MUSIC VIDEO" },
      { filmTitle: "Ink to Reel™ – Hiding in Holland", recipient: "Linda Radke", category: "BEST HUMAN RIGHTS FILM" },
      { filmTitle: "Not In My Country!", recipient: "Stijn van Baarle", category: "BEST ENVIRONMENT AND CLIMATE" },
      { filmTitle: "She Was", recipient: "Abril Arnauda", category: "BEST SHORT FILM" },
      { filmTitle: "Aperung", recipient: "Caroline Auer, Annika Ziegltrum", category: "BEST ACTRESS – SHORT FILM" },
      { filmTitle: "Dawn of Cyberwarfare", recipient: "Fabrizio Dublino", category: "BEST DOCUMENTARY" },
    ],
  },
  {
    year: 2025, month: 2, title: "February 2025", slug: "2025-02", published: true,
    winners: [
      { filmTitle: "Lockdown", recipient: "Melanie Jeffcoat", category: "BEST ACTRESS" },
      { filmTitle: "Lockdown", recipient: "Melanie Jeffcoat", category: "BEST DIRECTOR, SHORT FILM" },
      { filmTitle: "Oars and Ears", recipient: "Hunter Complex", category: "BEST MUSIC SCORE SHORT FILM" },
      { filmTitle: "The Light in the Dark", recipient: "Yudoten Chiu", category: "BEST ANIMATION" },
      { filmTitle: "Seabird – The Civil Eye", recipient: "Simon Straetker, David Lohmüller", category: "BEST HUMAN RIGHTS" },
      { filmTitle: "Gift A Feeling", recipient: "Alex Fouquet", category: "BEST COMMERCIAL & ADVERTISING" },
      { filmTitle: "WITH THEM", recipient: "Violette Pallaro", category: "BEST STUDENT FILM" },
      { filmTitle: "THE SIGHT IS A WOUND", recipient: "Parham Ghalamdar", category: "BEST EXPERIMENTAL FILM" },
      { filmTitle: "Raindrop – The Journey of Water", recipient: "Marco Dominik Graf", category: "BEST CINEMATOGRAPHY" },
      { filmTitle: "Raindrop – The Journey of Water", recipient: "Marco Dominik Graf", category: "BEST ENVIRONMENT AND CLIMATE" },
      { filmTitle: "BONES", recipient: "Christian Glatzel", category: "BEST COMEDY SHORT FILM" },
      { filmTitle: "LXV MACHINA – The Fisherman", recipient: "Béla Baptiste, Cristian Balint", category: "BEST MUSIC VIDEO" },
      { filmTitle: "The Cost of a Dream", recipient: "Adrian Pucheu", category: "BEST FIRST TIME DIRECTOR" },
      { filmTitle: "The Colours of Grief", recipient: "Mariana Lima Mateus", category: "BEST SHORT DOCUMENTARY" },
      { filmTitle: "Jhankar – the melody of resonance", recipient: "Hem Chandra Borah", category: "BEST FEATURE FILM" },
      { filmTitle: "Jhankar – the melody of resonance", recipient: "Hem Chandra Borah", category: "BEST DIRECTOR – FEATURE FILM" },
      { filmTitle: "Where the kids have no name", recipient: "Jamillah van der Hulst", category: "BEST DOCUMENTARY – SOCIAL" },
      { filmTitle: "Abundance", recipient: "Dora Jung", category: "BEST DOCUMENTARY – CULTURE" },
      { filmTitle: "Зверь / Beast", recipient: "Dmitry Pasichnyuk", category: "BEST SHORT FILM" },
      { filmTitle: "La valse des adieux", recipient: "Louis Salvatore Bellanti", category: "BEST SHORT FILM – EX AEQUO" },
    ],
  },
];

async function main() {
  await prisma.edition.deleteMany({ where: { slug: "2026-06" } });

  for (const ed of editions) {
    const existing = await prisma.edition.findUnique({ where: { slug: ed.slug } });
    if (existing) {
      console.log(`Skipping ${ed.title} — already exists`);
      continue;
    }
    await prisma.edition.create({
      data: {
        year: ed.year, month: ed.month, title: ed.title,
        slug: ed.slug, published: ed.published,
        winners: { create: ed.winners.map((w, i) => ({ ...w, order: i })) },
      },
    });
    console.log(`Imported ${ed.title}: ${ed.winners.length} winners`);
  }
  console.log("Done.");
}

main()
  .then(() => prisma.$disconnect())
  .catch(async (e) => { console.error(e); await prisma.$disconnect(); process.exit(1); });
